showConsole: true
layout:
  scope: section
theme:
  colors:
    text: 
      primary: '#333333'
  typography: 
    headings:
      fontFamily: 'Roboto'
    fontFamily: 'Roboto, Verdana, Geneva, sans-serif'
    fontSize: '14px'
redocURL: https://redocpro-cdn.redoc.ly/v1.0.0-beta.7/redocpro-standalone.min.js
redocExport: RedocPro
unstable_externalDescription: description.md
